# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|

  ## Ubuntu 12.04 LTS (64-bit)
  # custom ubuntu box with puppet 2.7.19
  config.vm.box = "alvi-ubuntu-server-12.04"
  config.vm.box_url = "alvi-ubuntu-server-12.04.box"

  # todo: change to url if open source
  # config.vm.box_url = "https://github.com/downloads/asm89/alvi-image-processor-cloud/alvi-ubuntu-server-12.04.box"

  # network
  config.vm.network :hostonly, "172.16.1.23", :netmask => "255.255.0.0"

  # set memory to 1GB
  config.vm.customize ["modifyvm", :id, "--memory", 1024]

  # Set the default project share
  config.vm.share_folder "data", "/data", "../"

  # Update deps
  # config.vm.provision :shell, :inline => "apt-get update --fix-missing"

  # Enable Puppet
  config.vm.provision :puppet do |puppet|
    puppet.facter = { "fqdn" => "master", "hostname" => "master" }
    puppet.manifests_path = "puppet/manifests"
    puppet.manifest_file  = "master.pp"
    puppet.module_path  = "puppet/modules"
  end

  # misc
  config.ssh.max_tries = 10
  config.vm.customize ["modifyvm", :id, "--rtcuseutc", "on"]
end
