imports:
    - { resource: parameters.yml }

framework:
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            false
    csrf_protection: false
    validation:      { enable_annotations: false }
    default_locale:  %locale%
    trust_proxy_headers: false
    session:         ~

old_sound_rabbit_mq:
    connections:
        default:
            host:      'localhost'
            port:      5673
            user:      'guest'
            password:  'guest'
            vhost:     '/'

    producers:
        upload_picture:
            connection: default
            exchange_options: {name: 'upload-picture', type: direct}

    consumers:
        upload_picture:
            connection: default
            exchange_options: {name: 'upload-picture', type: direct}
            queue_options:    {name: 'upload-picture'}
            callback:         alvi.image_processor.worker

beberlei_metrics:
    default: statsd
    collectors:
        statsd:
            type: statsd
