imports:
    - { resource: parameters.yml }

framework:
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            false
    csrf_protection: false
    validation:      { enable_annotations: false }
    default_locale:  %locale%
    trust_proxy_headers: false
    session:         ~
