imports:
    - { resource: parameters.yml }

framework:
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            false
    csrf_protection: false
    validation:      { enable_annotations: false }
    default_locale:  %locale%
    trust_proxy_headers: false
    session:         ~

old_sound_rabbit_mq:
    connections:
        default:
            host:      %master_node%
            port:      5673
            user:      'guest'
            password:  'guest'
            vhost:     '/'

    producers:
        upload_picture:
            connection: default
            exchange_options: {name: 'upload-picture', type: direct}
            queue_options:    {name: 'deployer'}
        deployer:
            connection: default
            exchange_options: {name: 'deployer', type: direct}
            queue_options:    {name: 'deployer'}
        deployer_callback:
            connection: default
            exchange_options: {name: 'deployer_callback', type: direct}
            queue_options:    {name: 'deployer_callback'}

    consumers:
        upload_picture:
            connection: default
            exchange_options: {name: 'upload-picture', type: direct}
            queue_options:    {name: 'upload-picture'}
            callback:         alvi.image_processor.worker
        deployer:
            connection: default
            exchange_options: {name: 'deployer', type: direct}
            queue_options:    {name: 'deployer'}
            callback:         alvi.image_processor.provisioner.deployer.messaged.deploy
        deployer_callback:
            connection: default
            exchange_options: {name: 'deployer_callback', type: direct}
            queue_options:    {name: 'deployer_callback'}
            callback:         alvi.image_processor.provisioner.deployer.messaged.callback

beberlei_metrics:
    default: statsd
    collectors:
        statsd:
            type: statsd
            host: %master_node%

alvi_image_processor_zookeeper:
    hosts: %master_node%:2181

